<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Visits11.Server</RootNamespace>
    <AssemblyName>KubGAU-Server</AssemblyName>
    <ApplicationIcon>../Assets/app.ico</ApplicationIcon>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <Resource Include="../Assets/Fonts/*.ttf" Link="Assets/Fonts/%(Filename)%(Extension)" />
    <Resource Include="../branding/apk-logo.jpg" Link="Assets/kubgau-logo.jpg" />
    <Resource Include="../Assets/app.ico" Link="Assets/app.ico" />
  </ItemGroup>
</Project>
